import type { FavoriteItem, Tag } from '@/types';
import { v4 as uuidv4 } from 'uuid';
import { getStaticMapUrl, getWebsiteScreenshot } from './utils';

const now = Date.now();

export const sampleTags: Tag[] = [
    { id: uuidv4(), name: 'تعليم', color: '#3b82f6', count: 3 },
    { id: uuidv4(), name: 'ترفيه', color: '#ef4444', count: 2 },
    { id: uuidv4(), name: 'عمل', color: '#10b981', count: 2 },
    { id: uuidv4(), name: 'مطاعم', color: '#f59e0b', count: 1 },
    { id: uuidv4(), name: 'مقالات', color: '#8b5cf6', count: 2 },
    { id: uuidv4(), name: 'أدوات', color: '#06b6d4', count: 1 },
    { id: uuidv4(), name: 'ملاحظات', color: '#ec4899', count: 2 },
    { id: uuidv4(), name: 'وصفات', color: '#f97316', count: 1 },
];

export const sampleFavorites: FavoriteItem[] = [
    // ===== YouTube Videos =====
    {
        id: uuidv4(),
        type: 'youtube',
        title: 'تعلم البرمجة - أساسيات JavaScript',
        content: 'فيديو تعليمي شامل عن أساسيات لغة JavaScript للمبتدئين',
        url: 'https://youtube.com/watch?v=PkZNo7MFNFg',
        thumbnail: 'https://img.youtube.com/vi/PkZNo7MFNFg/mqdefault.jpg',
        tags: ['تعليم'],
        isPinned: true,
        createdAt: now - 86400000 * 2,
        updatedAt: now - 86400000 * 2,
        metadata: {
            videoId: 'PkZNo7MFNFg',
            channelName: 'Programming with Mosh',
            duration: '48:17',
        },
    },
    {
        id: uuidv4(),
        type: 'youtube',
        title: 'React في 100 ثانية',
        content: 'شرح سريع عن مكتبة React وأساسياتها',
        url: 'https://youtube.com/watch?v=Tn6-PIqc4UM',
        thumbnail: 'https://img.youtube.com/vi/Tn6-PIqc4UM/mqdefault.jpg',
        tags: ['تعليم', 'أدوات'],
        isPinned: false,
        createdAt: now - 86400000 * 5,
        updatedAt: now - 86400000 * 5,
        metadata: {
            videoId: 'Tn6-PIqc4UM',
            channelName: 'Fireship',
            duration: '2:18',
        },
    },
    {
        id: uuidv4(),
        type: 'youtube',
        title: 'وثائقي عن الفضاء - رحلة إلى المريخ',
        content: 'وثائقي رائع عن مهمات ناسا لاستكشاف المريخ',
        url: 'https://youtube.com/watch?v=SUelbSa-OkA',
        thumbnail: 'https://img.youtube.com/vi/SUelbSa-OkA/mqdefault.jpg',
        tags: ['ترفيه', 'تعليم'],
        isPinned: false,
        createdAt: now - 86400000 * 7,
        updatedAt: now - 86400000 * 7,
        metadata: {
            videoId: 'SUelbSa-OkA',
            channelName: 'National Geographic',
            duration: '45:22',
        },
    },

    // ===== Websites (with screenshot thumbnails) =====
    {
        id: uuidv4(),
        type: 'website',
        title: 'MDN Web Docs',
        content: 'https://developer.mozilla.org',
        url: 'https://developer.mozilla.org',
        thumbnail: getWebsiteScreenshot('https://developer.mozilla.org', 400, 300),
        tags: ['تعليم', 'أدوات'],
        isPinned: true,
        createdAt: now - 86400000 * 3,
        updatedAt: now - 86400000 * 3,
        metadata: {
            description: 'المرجع الشامل لتطوير الويب - HTML, CSS, JavaScript',
            favicon: 'https://developer.mozilla.org/favicon-48x48.png',
        },
    },
    {
        id: uuidv4(),
        type: 'website',
        title: 'GitHub - منصة المطورين',
        content: 'https://github.com',
        url: 'https://github.com',
        thumbnail: getWebsiteScreenshot('https://github.com', 400, 300),
        tags: ['عمل', 'أدوات'],
        isPinned: false,
        createdAt: now - 86400000 * 4,
        updatedAt: now - 86400000 * 4,
        metadata: {
            description: 'منصة استضافة المشاريع البرمجية والتعاون بين المطورين',
            favicon: 'https://github.githubassets.com/favicons/favicon.svg',
        },
    },
    {
        id: uuidv4(),
        type: 'website',
        title: 'web.dev - دليل تطوير الويب',
        content: 'https://web.dev',
        url: 'https://web.dev',
        thumbnail: getWebsiteScreenshot('https://web.dev', 400, 300),
        tags: ['مقالات', 'تعليم'],
        isPinned: false,
        createdAt: now - 86400000 * 6,
        updatedAt: now - 86400000 * 6,
        metadata: {
            description: 'دليل شامل لبناء تطبيقات ويب حديثة من Google',
            favicon: 'https://web.dev/images/favicon.png',
        },
    },

    // ===== Phone Numbers =====
    {
        id: uuidv4(),
        type: 'phone',
        title: 'د. أحمد العلي - طبيب أسرة',
        content: '+966501234567',
        tags: ['عمل'],
        isPinned: false,
        createdAt: now - 86400000 * 8,
        updatedAt: now - 86400000 * 8,
        metadata: { contactName: 'د. أحمد العلي' },
    },
    {
        id: uuidv4(),
        type: 'phone',
        title: 'مطعم الشرق - توصيل',
        content: '+966551234567',
        tags: ['مطاعم'],
        isPinned: false,
        createdAt: now - 86400000 * 10,
        updatedAt: now - 86400000 * 10,
        metadata: { contactName: 'مطعم الشرق' },
    },
    {
        id: uuidv4(),
        type: 'phone',
        title: 'خدمة العملاء - شركة التقنية',
        content: '+966112345678',
        tags: ['عمل'],
        isPinned: false,
        createdAt: now - 86400000 * 12,
        updatedAt: now - 86400000 * 12,
        metadata: { contactName: 'خدمة العملاء' },
    },

    // ===== Locations (with map thumbnails showing pin) =====
    {
        id: uuidv4(),
        type: 'location',
        title: 'مكتبة الملك فهد الوطنية',
        content: 'مكتبة الملك فهد الوطنية، الرياض',
        thumbnail: getStaticMapUrl(24.6877, 46.6856, 15),
        tags: ['ملاحظات'],
        isPinned: false,
        createdAt: now - 86400000 * 1,
        updatedAt: now - 86400000 * 1,
        metadata: {
            latitude: 24.6877,
            longitude: 46.6856,
            address: 'طريق الملك فهد، الرياض',
            city: 'الرياض',
            country: 'السعودية',
        },
    },
    {
        id: uuidv4(),
        type: 'location',
        title: 'برج خليفة',
        content: 'برج خليفة، دبي، الإمارات',
        thumbnail: getStaticMapUrl(25.1972, 55.2744, 15),
        tags: ['ترفيه'],
        isPinned: false,
        createdAt: now - 86400000 * 9,
        updatedAt: now - 86400000 * 9,
        metadata: {
            latitude: 25.1972,
            longitude: 55.2744,
            address: 'شارع الشيخ زايد، دبي',
            city: 'دبي',
            country: 'الإمارات',
        },
    },
    {
        id: uuidv4(),
        type: 'location',
        title: 'المسجد الحرام',
        content: 'المسجد الحرام، مكة المكرمة',
        thumbnail: getStaticMapUrl(21.4225, 39.8262, 15),
        tags: ['ملاحظات'],
        isPinned: true,
        createdAt: now - 86400000 * 11,
        updatedAt: now - 86400000 * 11,
        metadata: {
            latitude: 21.4225,
            longitude: 39.8262,
            address: 'المسجد الحرام، مكة المكرمة',
            city: 'مكة المكرمة',
            country: 'السعودية',
        },
    },

    // ===== Text Notes =====
    {
        id: uuidv4(),
        type: 'text',
        title: 'أفكار لمشروع التخرج',
        content: '1. تطبيق إدارة المهام بالذكاء الاصطناعي\n2. نظام تتبع العادات اليومية\n3. منصة تعليمية تفاعلية\n4. تطبيق صحي لمتابعة التغذية',
        tags: ['عمل', 'ملاحظات'],
        isPinned: true,
        createdAt: now - 86400000 * 0.5,
        updatedAt: now - 86400000 * 0.5,
        metadata: {},
    },
    {
        id: uuidv4(),
        type: 'text',
        title: 'وصفة كيكة الشوكولاتة',
        content: 'المقادير:\n- 2 كوب دقيق\n- 1 كوب سكر\n- 3/4 كوب كاكاو\n- 2 بيضة\n- 1 كوب حليب\n- 1/2 كوب زيت\n\nالطريقة:\n1. اخلط المكونات الجافة\n2. أضف السائلة\n3. اخبز 180° لمدة 30 دقيقة',
        tags: ['وصفات'],
        isPinned: false,
        createdAt: now - 86400000 * 13,
        updatedAt: now - 86400000 * 13,
        metadata: {},
    },
    {
        id: uuidv4(),
        type: 'text',
        title: 'اقتباس ملهم',
        content: '"إن الطريقة الوحيدة للقيام بعمل عظيم هي أن تحب ما تفعله." - ستيف جوبز',
        tags: ['مقالات'],
        isPinned: false,
        createdAt: now - 86400000 * 14,
        updatedAt: now - 86400000 * 14,
        metadata: {},
    },

    // ===== Images =====
    {
        id: uuidv4(),
        type: 'image',
        title: 'تصميم واجهة المستخدم',
        content: 'تصميم الصفحة الرئيسية للمشروع الجديد',
        url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600',
        thumbnail: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
        tags: ['عمل'],
        isPinned: false,
        createdAt: now - 86400000 * 15,
        updatedAt: now - 86400000 * 15,
        metadata: {
            imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800',
            fileName: 'ui-design.jpg',
        },
    },
    {
        id: uuidv4(),
        type: 'image',
        title: 'غروب الشمس على البحر',
        content: 'صورة رائعة لغروب الشمس',
        url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600',
        thumbnail: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=400',
        tags: ['ترفيه'],
        isPinned: false,
        createdAt: now - 86400000 * 16,
        updatedAt: now - 86400000 * 16,
        metadata: {
            imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
            fileName: 'sunset-beach.jpg',
        },
    },
    {
        id: uuidv4(),
        type: 'image',
        title: 'خريطة ذهنية - خطة التطوير',
        content: 'خريطة ذهنية لخطة تطوير المشروع',
        url: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=600',
        thumbnail: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=400',
        tags: ['عمل', 'مقالات'],
        isPinned: false,
        createdAt: now - 86400000 * 17,
        updatedAt: now - 86400000 * 17,
        metadata: {
            imageUrl: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800',
            fileName: 'mindmap-plan.jpg',
        },
    },
];
